In [2]:
print('hello world')

hello world


In [5]:
import numpy as np

In [6]:
import mysql.connector

In [9]:
import time
import numpy as np

size_of_vec = 1000000

def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(x)) ]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arrange(size_of_vec)
    Y = np.arrange(size_of_vec)
    Z = X + Y
    return time.time() - t1

t1 = pure_python_version()
t2 = numpy_version()

t1 = pure_python_version()
t2 = numpy_version()
print(f'''Waktu running pure python adalah {round(t1,4)} detik.
Waktu running versi numpy adalah {round(t2,4)} detik.
Numpy di contoh ini {(round((t1/t2),4))} kali lebih cepat!''')

NameError: name 'x' is not defined

In [10]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [11]:
np.array(my_list)

array([1, 2, 3])

In [13]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
my_list3 = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
]

In [18]:
np.array(my_list3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones(3)

array([1., 1., 1.])

In [26]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [29]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [30]:
np.random.rand(4)

array([2.10497985e-01, 8.64988745e-01, 7.47439036e-01, 6.05540148e-05])

In [31]:
np.random.rand(5,5)

array([[0.62935947, 0.15719186, 0.52425636, 0.0788424 , 0.20921259],
       [0.91115966, 0.10719109, 0.36510161, 0.12134062, 0.99217483],
       [0.54984323, 0.1195314 , 0.96109263, 0.09610535, 0.0506619 ],
       [0.86969788, 0.88786761, 0.66062033, 0.7973361 , 0.73269378],
       [0.68337087, 0.71914027, 0.54740226, 0.92174014, 0.5239702 ]])

In [32]:
np.random.randn(2)

array([0.02152273, 1.62478355])

In [33]:
np.random.randn(5,5)

array([[ 0.34471954, -0.72568898, -2.04471765,  1.47134783,  0.18226221],
       [-0.47190964, -0.36214871,  0.49145848,  1.76373285,  1.48375569],
       [ 0.17889531, -0.38464417,  2.04900371,  0.09245019,  0.82415357],
       [-0.2526841 , -0.69644579, -0.64120393,  0.31056477,  0.99227511],
       [ 0.91170264,  1.58641351,  1.01965924,  0.28730117, -1.23784413]])

In [34]:
np.random.randint(1,100)

69

In [35]:
np.random.randint(1,100,10)

array([95, 73, 24, 16, 74, 66, 93, 49, 57, 28])

In [36]:
arr

NameError: name 'arr' is not defined

In [37]:
arr.shape

NameError: name 'arr' is not defined

In [38]:
my_list = [1,2,3]
array_1d = np.array(my_list)

my_list2 = [[1,2,3],[4,5,3],[7,8,9]]
array_2d = np.array(my_list2)

my_list3 = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
]
array_3d = np.array(my_list3)

In [39]:
array_1d.shape

(3,)

In [40]:
array_2d.shape

(3, 3)

In [41]:
array_3d.shape

(3, 3, 3)

In [42]:
arr

NameError: name 'arr' is not defined

In [43]:
arr.reshape(5,5)

NameError: name 'arr' is not defined

In [44]:
array_2d.reshape(-1)

array([1, 2, 3, 4, 5, 3, 7, 8, 9])

In [45]:
arr = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]

arr

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24]

In [46]:
arr.array()

AttributeError: 'list' object has no attribute 'array'

In [47]:
import numpy as np

In [49]:
arr = np.arange(0,11)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr[8]

8

In [52]:
arr[0]

0

In [53]:
arr[2:3]

array([2])

In [54]:
arr[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [55]:
arr[0:10:3]

array([0, 3, 6, 9])

In [56]:
arr[0:2] = 100

arr

array([100, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [57]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [59]:
slice_of_arr[:] = 99

slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [60]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [61]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [63]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [64]:
arr_2d[1]

array([20, 25, 30])

In [65]:
arr_2d[1][0]

20

In [66]:
arr_2d[1,0]

20

In [67]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [68]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [69]:
arr_2d[:,2]

array([15, 30, 45])

In [70]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [75]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
[arr[2],arr[5],arr[9]]

[2, 5, 9]

In [77]:
arr[[2,5,9]]

array([2, 5, 9])

In [78]:
arr[[5,9,2]]

array([5, 9, 2])

In [79]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [80]:
arr_2d[[0,2]]

array([[ 5, 10, 15],
       [35, 40, 45]])

In [81]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [83]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [85]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [86]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])